use countries;
db.dropDatabase();

db.country_list.insertMany([
  {name: "Afghanistan"},
  {name: "Aland Islands"},
  {name: "Albania"},
  {name: "Algeria"},
  {name: "Andorra"},
  {name: "Angola"},
  {name: "Antigua And Barbuda"},
  {name: "Argentina"},
  {name: "Armenia"},
  {name: "Aruba"},
  {name: "Australia"},
  {name: "Austria"},
  {name: "Azerbaijan"},
  {name: "Bahamas"},
  {name: "Bahrain"},
  {name: "Bangladesh"},
  {name: "Barbados"},
  {name: "Belarus"},
  {name: "Belgium"},
  {name: "Belize"},
  {name: "Bermuda"},
  {name: "Bhutan"},
  {name: "Bolivia"},
  {name: "Bonaire"},
  // {name: "Bosnia And Herzegovina"},
  // {name: "Botswana"},
  // {name: "Brazil"},
  // {name: "Brunei"},
  // {name: "Bulgaria"},
  // {name: "Burkina Faso"},
  // {name: "Burundi"},
  // {name: "Cambodia"},
  // {name: "Cameroon"},
  // {name: "Canada"},
  // {name: "Cayman Islands"},
  // {name: "Chad"},
  // {name: "Chile"},
  // {name: "China"},
  // {name: "Colombia"},
  // {name: "Congo"},
  // {name: "Costa Rica"},
  // {name: "Croatia"},
  // {name: "Cuba"},
  // {name: "Curacao"},
  // {name: "Cyprus"},
  // {name:  "Czech Republic"},
  // {name: "Denmark"},
  // {name: "Djibouti"},
  // {name: "Dominica"},
  // {name: "Dominican Republic"},
  // {name: "Ecuador"},
  // {name: "Egypt"},
  // {name: "El Salvador"},
  // {name: "Equatorial Guinea"},
  // {name: "Estonia"},
  // {name: "Ethiopia"},
  // {name: "Faroe Islands"},
  // {name: "Fiji"},
  // {name: "Finland"},
  // {name: "France"},
  // {name: "French Polynesia"},
  // {name: "Gabon"},
  // {name:  "Gambia"},
  // {name: "Georgia"},
  // {name: "Germany"},
  // {name: "Ghana"},
  // {name: "Gibraltar"},
  // {name: "Greece"},
  // {name: "Greenland"},
  // {name: "Grenada"},
  // {name: "Guam"},
  // {name: "Guatemala"},
  // {name: "Guernsey"},
  // {name: "Guinea-Bissau"},
  // {name: "Guyana"},
  // {name: "Haiti"},
  // {name: "Honduras"},
  // {name: "Hong Kong"},
  // {name: "Hungary"},
  // {name: "Iceland"},
  // {name: "India"},
  // {name: "Indonesia"},
  // {name: "Iran"},
  // {name: "Iraq"},
  // {name: "Ireland"},
  // {name: "Isle Of Man"},
  // {name: "Israel"},
  // {name: "Italy"},
  // {name: "Ivory Coast"},
  // {name: "Jamaica"},
  // {name: "Japan"},
  // {name: "Jersey"},
  // {name: "Jordan"},
  // {name: "Kazakhstan"},
  // {name: "Kenya"},
  // {name: "Kosovo (Disputed Territory)"},
  // {name: "Kuwait"},
  // {name: "Kyrgyzstan"},
  // {name: "Laos"},
  // {name: "Latvia"},
  // {name: "Lebanon"},
  // {name: "Lesotho"},
  // {name: "Liberia"},
  // {name: "Libya"},
  // {name: "Lithuania"},
  // {name: "Luxembourg"},
  // {name: "Macao"},
  // {name: "Macedonia"},
  // {name: "Madagascar"},
  // {name: "Malawi"},
  // {name: "Malaysia"},
  // {name: "Maldives"},
  // {name: "Mali"},
  // {name: "Malta"},
  // {name: "Mauritania"},
  // {name: "Mauritius"},
  // {name: "Mexico"},
  // {name: "Moldova"},
  // {name: "Monaco"},
  // {name: "Mongolia"},
  // {name: "Montenegro"},
  // {name:  "Morocco"},
  // {name: "Mozambique"},
  // {name: "Myanmar"},
  // {name: "Namibia"},
  // {name: "Nepal"},
  // {name: "Netherlands"},
  // {name: "New Caledonia"},
  // {name: "New Zealand"},
  // {name: "Nicaragua"},
  // {name: "Nigeria"},
  // {name: "Northern Mariana Islands"},
  // {name: "Norway"},
  // {name: "Oman"},
  // {name: "Pakistan"},
  // {name: "Palestinian Territory"},
  // {name: "Panama"},
  // {name: "Papua New Guinea"},
  // {name: "Paraguay"},
  // {name: "Peru"},
  // {name: "Philippines"},
  // {name: "Poland"},
  // {name: "Portugal"},
  // {name: "Puerto Rico"},
  // {name: "Qatar"},
  // {name: "Reunion"},
  // {name: "Romania"},
  // {name: "Russia"},
  // {name: "Rwanda"},
  // {name: "Saint Kitts And Nevis"},
  // {name: "Saint Lucia"},
  // {name: "Saint Vincent And The Grenadines"},
  // {name: "Samoa"},
  // {name: "Saudi Arabia"},
  // {name: "Senegal"},
  // {name: "Serbia"},
  // {name: "Seychelles"},
  // {name: "Singapore"},
  // {name: "Sint Maarten"},
  // {name: "Slovakia"},
  // {name: "Slovenia"},
  // {name: "Solomon Islands"},
  // {name: "Somalia"},
  // {name: "South Africa"},
  // {name: "South Korea"},
  // {name: "Spain"},
  // {name: "Sri Lanka"},
  // {name: "Sudan"},
  // {name: "Suriname"},
  // {name: "Swaziland"},
  // {name: "Sweden"},
  // {name: "Switzerland"},
  // {name: "Syria"},
  // {name: "Taiwan"},
  // {name: "Tajikistan"},
  // {name: "Tanzania"},
  // {name: "Thailand"},
  // {name: "Timor-Leste"},
  // {name: "Togo"},
  // {name: "Tonga"},
  // {name: "Trinidad And Tobago"},
  // {name: "Tunisia"},
  // {name: "Turkey"},
  // {name: "Turkmenistan"},
  // {name: "Turks And Caicos Islands"},
  // {name: "Uganda"},
  // {name: "Ukraine"},
  // {name: "United Arab Emirates"},
  // {name: "United Kingdom"},
  // {name:"United States"},
  // {name: "Uruguay"},
  // {name: "Us Virgin Islands"},
  // {name: "Uzbekistan"},
  // {name: "Vanuatu"},
  // {name: "Venezuela"},
  // {name: "Vietnam"},
  // {name: "Yemen"},
  // {name: "Zambia"},
  {name: "Zimbabwe"}
]
)
